### ISSUE TITLE
Spellcasting Crash

### ISSUE THREAD

**Issue by RubyMartinWolf** [domanhthang2110/efiscompat#6]
First: Can't cast spells alone or even from a book. Need a staff
Second: If spell gets cast, game crashes.

No other mods can be causing this issue, tested

**Comment by RubyMartinWolf** [comment]
Also, crash report says something about something missing

**Comment by domanhthang2110** [comment]
Can you provide your crash log file?

**Comment by RubyMartinWolf** [comment]
> Can you provide your crash log file?

Just to be sure il tell you that I could not cast spells on their own or from a book, ihad to have a book in my curio inventotry and then use a staff, and then it c rashes.



---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2024-12-30 09:54:09
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "java.util.List.contains(Object)" because "stringList" is null
	at com.yukami.epicironcompat.utils.CompatUtils.isHoldingStaffOffHand(CompatUtils.java:24) ~[efiscompat-2.2.1.jar%23186!/:2.2.1] {re:mixin,re:classloading}
	at yesman.epicfight.client.renderer.patched.item.RenderItemBase.handler$zzm000$onRenderItemInHandStart(RenderItemBase.java:541) ~[epicfight-forge-20.9.6-1.20.1.jar%23188!/:20.9.6] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.epicironcompat.json:MixinRenderItemBase,pl:mixin:A,pl:runtimedistcleaner:A}
	at yesman.epicfight.client.renderer.patched.item.RenderItemBase.renderItemInHand(RenderItemBase.java) ~[epicfight-forge-20.9.6-1.20.1.jar%23188!/:20.9.6] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.epicironcompat.json:MixinRenderItemBase,pl:mixin:A,pl:runtimedistcleaner:A}
	at yesman.epicfight.client.renderer.patched.layer.PatchedItemInHandLayer.renderLayer(PatchedItemInHandLayer.java:39) ~[epicfight-forge-20.9.6-1.20.1.jar%23188!/:20.9.6] {re:classloading,pl:runtimedistcleaner:A}
	at yesman.epicfight.client.renderer.patched.layer.PatchedLayer.renderLayer(PatchedLayer.java:19) ~[epicfight-forge-20.9.6-1.20.1.jar%23188!/:20.9.6] {re:classloading,pl:runtimedistcleaner:A}
	at yesman.epicfight.client.renderer.FirstPersonRenderer.renderLayer(FirstPersonRenderer.java:120) ~[epicfight-forge-20.9.6-1.20.1.jar%23188!/:20.9.6] {re:classloading,pl:runtimedistcleaner:A}
	at yesman.epicfight.client.renderer.FirstPersonRenderer.render(FirstPersonRenderer.java:95) ~[epicfight-forge-20.9.6-1.20.1.jar%23188!/:20.9.6] {re:classloading,pl:runtimedistcleaner:A}
	at yesman.epicfight.client.events.engine.RenderEngine$Events.renderHand(RenderEngine.java:694) ~[epicfight-forge-20.9.6-1.20.1.jar%23188!/:20.9.6] {re:classloading}
	at yesman.epicfight.client.events.engine.__Events_renderHand_RenderHandEvent.invoke(.dynamic) ~[epicfight-forge-20.9.6-1.20.1.jar%23188!/:20.9.6] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23148!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23148!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23148!/:?] {}
	at net.minecraftforge.client.ForgeHooksClient.renderSpecificFirstPersonHand(ForgeHooksClient.java:301) ~[forge-1.20.1-47.3.22-universal.jar%23205!/:?] {re:classloading}
	at net.minecraft.client.renderer.ItemInHandRenderer.m_109314_(ItemInHandRenderer.java:316) ~[client-1.20.1-20230612.114412-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:playerAnimator-common.mixins.json:firstPerson.ItemInHandRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109120_(GameRenderer.java:852) ~[client-1.20.1-20230612.114412-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1132) ~[client-1.20.1-20230612.114412-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:909) ~[client-1.20.1-20230612.114412-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.epicfight.json:MixinMinecraft,pl:mixin:APP:mixins.irons_spellbooks.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.epicfight.json:MixinMinecraft,pl:mixin:APP:mixins.irons_spellbooks.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-47.3.22.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.22.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.22.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.22.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mods: 
	Epic Fight & Iron's Spellbook animation compat (efiscompat), Version: 2.2.1
		at TRANSFORMER/efiscompat@2.2.1/com.yukami.epicironcompat.utils.CompatUtils.isHoldingStaffOffHand(CompatUtils.java:24)

	Epic Fight (epicfight), Version: 20.9.6
		Issue tracker URL: https://github.com/Yesssssman/epicfightmod/issues
		at TRANSFORMER/epicfight@20.9.6/yesman.epicfight.client.renderer.patched.item.RenderItemBase.handler$zzm000$onRenderItemInHandStart(RenderItemBase.java:541)
Stacktrace:
	at com.yukami.epicironcompat.utils.CompatUtils.isHoldingStaffOffHand(CompatUtils.java:24) ~[efiscompat-2.2.1.jar%23186!/:2.2.1] {re:mixin,re:classloading}
	at yesman.epicfight.client.renderer.patched.item.RenderItemBase.handler$zzm000$onRenderItemInHandStart(RenderItemBase.java:541) ~[epicfight-forge-20.9.6-1.20.1.jar%23188!/:20.9.6] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.epicironcompat.json:MixinRenderItemBase,pl:mixin:A,pl:runtimedistcleaner:A}
	at yesman.epicfight.client.renderer.patched.item.RenderItemBase.renderItemInHand(RenderItemBase.java) ~[epicfight-forge-20.9.6-1.20.1.jar%23188!/:20.9.6] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.epicironcompat.json:MixinRenderItemBase,pl:mixin:A,pl:runtimedistcleaner:A}
	at yesman.epicfight.client.renderer.patched.layer.PatchedItemInHandLayer.renderLayer(PatchedItemInHandLayer.java:39) ~[epicfight-forge-20.9.6-1.20.1.jar%23188!/:20.9.6] {re:classloading,pl:runtimedistcleaner:A}
	at yesman.epicfight.client.renderer.patched.layer.PatchedLayer.renderLayer(PatchedLayer.java:19) ~[epicfight-forge-20.9.6-1.20.1.jar%23188!/:20.9.6] {re:classloading,pl:runtimedistcleaner:A}
	at yesman.epicfight.client.renderer.FirstPersonRenderer.renderLayer(FirstPersonRenderer.java:120) ~[epicfight-forge-20.9.6-1.20.1.jar%23188!/:20.9.6] {re:classloading,pl:runtimedistcleaner:A}
	at yesman.epicfight.client.renderer.FirstPersonRenderer.render(FirstPersonRenderer.java:95) ~[epicfight-forge-20.9.6-1.20.1.jar%23188!/:20.9.6] {re:classloading,pl:runtimedistcleaner:A}
	at yesman.epicfight.client.events.engine.RenderEngine$Events.renderHand(RenderEngine.java:694) ~[epicfight-forge-20.9.6-1.20.1.jar%23188!/:20.9.6] {re:classloading}
	at yesman.epicfight.client.events.engine.__Events_renderHand_RenderHandEvent.invoke(.dynamic) ~[epicfight-forge-20.9.6-1.20.1.jar%23188!/:20.9.6] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23148!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23148!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23148!/:?] {}
	at net.minecraftforge.client.ForgeHooksClient.renderSpecificFirstPersonHand(ForgeHooksClient.java:301) ~[forge-1.20.1-47.3.22-universal.jar%23205!/:?] {re:classloading}
	at net.minecraft.client.renderer.ItemInHandRenderer.m_109314_(ItemInHandRenderer.java:316) ~[client-1.20.1-20230612.114412-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:playerAnimator-common.mixins.json:firstPerson.ItemInHandRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109120_(GameRenderer.java:852) ~[client-1.20.1-20230612.114412-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1132) ~[client-1.20.1-20230612.114412-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['{MINECRAFT_USERNAME}'/61, l='ClientLevel', x=103.35, y=64.00, z=-15.46]]
	Chunk stats: 961, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (96,63,-15), Section: (at 0,15,1 in 6,3,-1; chunk contains blocks 96,-64,-16 to 111,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 1172 game time, 1172 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:455) ~[client-1.20.1-20230612.114412-srg.jar%23200!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:citadel.mixins.json:client.ClientLevelMixin,pl:mixin:APP:entityculling.mixins.json:ClientWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2319) ~[client-1.20.1-20230612.114412-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.epicfight.json:MixinMinecraft,pl:mixin:APP:mixins.irons_spellbooks.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:740) ~[client-1.20.1-20230612.114412-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.epicfight.json:MixinMinecraft,pl:mixin:APP:mixins.irons_spellbooks.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-47.3.22.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.22.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.22.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.22.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, mod_resources

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.12, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 914596360 bytes (872 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 2060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e89
	Graphics card #0 versionInfo: DriverVersion=32.0.15.6094
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 19637.80
	Virtual memory used (MB): 11065.88
	Swap memory total (MB): 3328.00
	Swap memory used (MB): 20.89
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048M
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce RTX 2060/PCIe/SSE2 GL version 4.6.0 NVIDIA 560.94, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: en_us
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['{MINECRAFT_USERNAME}'/61, l='ServerLevel[New World]', x=103.35, y=64.00, z=-15.46]]
	Data Packs: vanilla, mod:farmersdelight, mod:mr_ctov_farmersdelightcompat, mod:radiantgear (incompatible), mod:efiscompat, mod:geckolib, mod:playeranimator (incompatible), mod:lithostitched, mod:caelus (incompatible), mod:curiouslanterns, mod:curios (incompatible), mod:patchouli (incompatible), mod:epicfight, mod:citadel (incompatible), mod:irons_spellbooks, mod:entityculling, mod:rare_ice (incompatible), mod:iceandfire, mod:ice_and_fire_spellbooks, mod:mr_ctov_ironsspellsnspellbookscompat, mod:cloth_config (incompatible), mod:forge, mod:ctov, mod:ice_and_fire_delight, lithostitched/breaks_seed_parity
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.3.22.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.22.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.3.22.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.3.22.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.22.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		FarmersDelight-1.20.1-1.2.6.jar                   |Farmer's Delight              |farmersdelight                |1.20.1-1.2.6        |DONE      |Manifest: NOSIGNATURE
		ctov-farmers-delight-compat-2.1.jar               |CTOV - Farmer Delight Compat  |mr_ctov_farmersdelightcompat  |2.1                 |DONE      |Manifest: NOSIGNATURE
		radiantgear-forge-2.2.0+1.20.1.jar                |Radiant Gear                  |radiantgear                   |2.2.0+1.20.1        |DONE      |Manifest: NOSIGNATURE
		efiscompat-2.2.1.jar                              |Epic Fight & Iron's Spellbook |efiscompat                    |2.2.1               |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.20.1-4.7.jar                     |GeckoLib 4                    |geckolib                      |4.7                 |DONE      |Manifest: NOSIGNATURE
		player-animation-lib-forge-1.0.2-rc1+1.20.jar     |Player Animator               |playeranimator                |1.0.2-rc1+1.20      |DONE      |Manifest: NOSIGNATURE
		lithostitched-forge-1.20.1-1.3.10.jar             |Lithostitched                 |lithostitched                 |1.3.8               |DONE      |Manifest: NOSIGNATURE
		caelus-forge-3.2.0+1.20.1.jar                     |Caelus API                    |caelus                        |3.2.0+1.20.1        |DONE      |Manifest: NOSIGNATURE
		curiouslanterns-1.20.1-1.3.3.jar                  |Curious Lanterns              |curiouslanterns               |1.20.1-1.3.3        |DONE      |Manifest: NOSIGNATURE
		curios-forge-5.11.0+1.20.1.jar                    |Curios API                    |curios                        |5.11.0+1.20.1       |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.20.1-84-FORGE.jar                     |Patchouli                     |patchouli                     |1.20.1-84-FORGE     |DONE      |Manifest: NOSIGNATURE
		epicfight-forge-20.9.6-1.20.1.jar                 |Epic Fight                    |epicfight                     |20.9.6              |DONE      |Manifest: NOSIGNATURE
		citadel-2.6.1-1.20.1.jar                          |Citadel                       |citadel                       |2.6.1               |DONE      |Manifest: NOSIGNATURE
		irons_spellbooks-1.20.1-3.4.0.jar                 |Iron's Spells 'n Spellbooks   |irons_spellbooks              |1.20.1-3.4.0        |DONE      |Manifest: NOSIGNATURE
		entityculling-forge-1.7.2-mc1.20.1.jar            |EntityCulling                 |entityculling                 |1.7.2               |DONE      |Manifest: NOSIGNATURE
		rare-ice-0.6.0.jar                                |Rare Ice                      |rare_ice                      |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		iceandfire-2.1.13-1.20.1-beta-5.jar               |Ice and Fire                  |iceandfire                    |2.1.13-1.20.1       |DONE      |Manifest: NOSIGNATURE
		ice_and_fire_spellbooks-2.3.1-1.20.1.jar          |Ice and Fire: Spellbooks      |ice_and_fire_spellbooks       |2.3.1-1.20.1        |DONE      |Manifest: NOSIGNATURE
		ctov-irons-spells-n-spellbooks-compat-1.2.jar     |CTOV - Iron's Spells 'n Spellb|mr_ctov_ironsspellsnspellbooks|1.2                 |DONE      |Manifest: NOSIGNATURE
		cloth-config-11.1.136-forge.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.136            |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.3.22-universal.jar                |Forge                         |forge                         |47.3.22             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		[forge]ctov-3.4.10.jar                            |ChoiceTheorem's Overhauled Vil|ctov                          |3.4.10              |DONE      |Manifest: NOSIGNATURE
		ice_and_fire_delight-forge-1.20.1-0.1.9.jar       |Ice and Fire Delight          |ice_and_fire_delight          |0.1.9               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 10d896bd-9e2e-4a3b-9556-79d8411a6ab3
	FML: 47.3
	Forge: net.minecraftforge:47.3.22

**Comment by domanhthang2110** [comment]
Can you delete the config file named efiscompat and try again? This might happen if you upgrade from an old version

**Comment by RubyMartinWolf** [comment]
> Can you delete the config file named efiscompat and try again? This might happen if you upgrade from an old version

Okay I'll try but I doubt it

**Comment by RubyMartinWolf** [comment]
> Can you delete the config file named efiscompat and try again? This might happen if you upgrade from an old version

Yup, didnt help at all.
Edit: Soo actually it seems the file keeps returning no matter how many times I delete it
Edit2: Even when I delete the file after launch, it doesnt help

**Comment by domanhthang2110** [comment]
I just noticed that you have version 2.2.1 of efiscompat, maybe try upgrading to the latest one?
If the error still happen you can upload the content of the config file here

**Comment by RubyMartinWolf** [comment]
> I just noticed that you have version 2.2.1 of efiscompat, maybe try upgrading to the latest one? If the error still happen you can upload the content of the config file here

How do I update?

**Comment by domanhthang2110** [comment]
Go on Curseforge and download the latest version :D
https://www.curseforge.com/minecraft/mc-mods/epic-fight-x-irons-spells-animation-fix

**Comment by RubyMartinWolf** [comment]
> Go on Curseforge and download the latest version :D https://www.curseforge.com/minecraft/mc-mods/epic-fight-x-irons-spells-animation-fix

I always had thelatest version.

**Comment by domanhthang2110** [comment]
The latest is 2.2.3, you had 2.2.1 in your crash log

**Comment by RubyMartinWolf** [comment]
> The latest is 2.2.3, you had 2.2.1 in your crash log

There is no 2.2.3 though

**Comment by domanhthang2110** [comment]
![image](https://github.com/user-attachments/assets/13fe9dcc-f64d-4144-b02e-abb73b7ad598)
I don't know what to tell you man XD
What platform are you using
